services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydb
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://dbuser:12345@db:5432/mydb?schema=public
    depends_on:
      - db

volumes:
  pg_data:
